## © 2022 Nokia
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: deploy nephio-configsync on {{ item.key }} cluster
  shell: kpt --kubeconfig ~/.kube/{{ item.key }}-config live init nephio-configsync
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already" not in result.stderr

- name: deploy nephio-configsync on {{ item.key }} cluster
  shell: kpt --kubeconfig ~/.kube/{{ item.key }}-config live apply nephio-configsync --reconcile-timeout=15m --output=table
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"

- name: configure secret on {{ item.key }}
  shell: |
    kubectl --kubeconfig ~/.kube/{{ item.key }}-config create secret generic github-personal-access-token \
    --namespace="config-management-system" \
    --from-literal=username={{github_username}} \
    --from-literal=token={{github_token}}
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr
  when:
    - github_username is defined

- name: configure nephio-configsync
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/{{ item.key }}-config apply -f -
      apiVersion: configsync.gke.io/v1beta1
      kind: RootSync
      metadata: # kpt-merge: config-management-system/nephio-mgmt-cluster-sync
        name: repo-{{ item.key }}-sync
        namespace: config-management-system
        annotations:
          config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
          internal.kpt.dev/upstream-identifier: 'configsync.gke.io|RootSync|config-management-system|nephio-mgmt-cluster-sync'
      spec:
        sourceFormat: unstructured
        git:
          repo: https://github.com/{{ github_organization}}/nephio-{{ item.key }}.git
          branch: main
          auth: token
          secretRef:
            name: github-personal-access-token
    EOF
  when:
    - github_username is defined
    - github_organization is defined

- name: configure nephio-configsync
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/{{ item.key }}-config apply -f -
      apiVersion: configsync.gke.io/v1beta1
      kind: RootSync
      metadata: # kpt-merge: config-management-system/nephio-mgmt-cluster-sync
        name: repo-{{ item.key }}-sync
        namespace: config-management-system
        annotations:
          config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
          internal.kpt.dev/upstream-identifier: 'configsync.gke.io|RootSync|config-management-system|nephio-mgmt-cluster-sync'
      spec:
        sourceFormat: unstructured
        git:
          repo: https://github.com/{{ github_username }}/nephio-{{ item.key }}.git
          branch: main
          auth: token
          secretRef:
            name: github-personal-access-token
    EOF
  when:
    - github_username is defined
    - github_organization is not defined

- name: Slurp gitea access token
  ansible.builtin.slurp:
    src: /home/{{ cloud_user }}/gitea/nephio-gitea-token
  register: gitea_token
  when:
    - gitea_username is defined

- name: configure secret on {{ item.key }}
  shell: |
    kubectl --kubeconfig ~/.kube/{{ item.key }}-config create secret generic gitea-access-token \
    --namespace="config-management-system" \
    --from-literal=username=nephio \
    --from-literal=token={{ gitea_token['content'] | b64decode }}
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr
  when:
    - gitea_username is defined

- name: configure gitea-nephio-configsync
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/{{ item.key }}-config apply -f -
      apiVersion: configsync.gke.io/v1beta1
      kind: RootSync
      metadata: # kpt-merge: config-management-system/nephio-mgmt-cluster-sync
        name: gitea-repo-{{ item.key }}-sync
        namespace: config-management-system
        annotations:
          config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
          internal.kpt.dev/upstream-identifier: 'configsync.gke.io|RootSync|config-management-system|nephio-mgmt-cluster-sync'
      spec:
        sourceFormat: unstructured
        git:
          repo: http://gitea:3000/nephio/nephio-{{ item.key }}.git
          branch: main
          auth: token
          secretRef:
            name: gitea-access-token
    EOF
  when:
    - gitea_username is defined
