## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: installing clab
  become: true
  shell: bash -c "$(wget -qO - https://get.containerlab.dev)"
  when: validate_certs


- name: Create clab installation directory
  become: true
  file:
    path: "{{ tmp_directory }}/clab_install"
    state: directory
  when: not validate_certs

- name: Download clab script
  become: true
  ansible.builtin.get_url:
    url: "https://get.containerlab.dev"
    dest: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
    mode: 0755
    validate_certs: false
  when: not validate_certs

- name: "Replace for curl insecure mode1"
  become: true
  replace:
    path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
    regexp: 'curl -s'
    replace: 'curl -ks'
    backup: yes
  when: not validate_certs

- name: "Replace for curl insecure mode2"
  become: true
  replace:
    path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
    regexp: 'curl -S'
    replace: 'curl -kS'
    backup: yes
  when: not validate_certs

- name: "Replace for wget insecure mode"
  become: true
  replace:
    path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
    regexp: 'wget -q'
    replace: 'wget --no-check-certificate -q'
    backup: yes
  when: not validate_certs

- name: Execute the clabinstaller.sh
  become: true
  shell: bash -c "{{ tmp_directory }}/clab_install/clabinstaller.sh"
  when: not validate_certs

- name: Remove the clabinstaller.sh
  become: true
  file:
    path: "{{ tmp_directory }}/clab_install"
    state: absent
  when: not validate_certs
